const express=require('express')
const adminRouter=express.Router()
const admin=require('../models/Admin')
const vendor=require('../models/Vendor')
const adminController=require('../controllers/AdminController')
const HotelController=require('../controllers/HotelController')
const CouponController=require('../controllers/CouponController')
const ChatController=require('../controllers/ChatController')

adminRouter.post('/signup',adminController.addAdmin)
adminRouter.post('/adminlogin',adminController.adminLogin)
adminRouter.get('/vendorrequest',adminController.vendorRequest)
adminRouter.get('/vendorManage',adminController.vendorManage)
adminRouter.get('/vendorview/:id',adminController.vendorView)
adminRouter.post('/vendorApproval',adminController.vendorApprove)
adminRouter.post('/addcategory',HotelController.Addcategory)
adminRouter.get('/getcategory',HotelController.getCategory)
adminRouter.get('/gethotelRequestData',HotelController.hotelDatarequestAdmin)
adminRouter.get('/gethotelData',HotelController.hotelDataAdmin)
adminRouter.get('/getUserData',adminController.UserManage)
adminRouter.put('/getUserStatus',adminController.UserStatusChange)
adminRouter.put('/getHotelStatus',HotelController.hotelStatusChange)
adminRouter.put('/getVendorStatus',adminController.VendorStatusChange)
adminRouter.post('/updateHotelproofstatus',HotelController.updateproofstatus)
adminRouter.post('/addCoupon',CouponController.AddCoupon)
adminRouter.get('/Coupons',CouponController.AllCoupon)
adminRouter.get('/cancelBooking',adminController.CancelBooking)

adminRouter.get('/bookings',adminController.BookingsDetails)
adminRouter.post('/CreateMessage',ChatController.createMessage)
adminRouter.get('/Messages',ChatController.getAllMessage)
adminRouter.get('/allChats',ChatController.findChats)
adminRouter.get('/dashbord',adminController.Dashbord)
module.exports=adminRouter