const express=require('express')
const adminRouter=express.Router()
const admin=require('../models/Admin')
const vendor=require('../models/Vendor')
const adminController=require('../controllers/AdminController')
const HotelController=require('../controllers/HotelController')

adminRouter.post('/signup',adminController.addAdmin)
adminRouter.post('/adminlogin',adminController.adminLogin)
adminRouter.get('/vendorrequest',adminController.vendorRequest)
adminRouter.get('/vendorManage',adminController.vendorManage)
adminRouter.get('/vendorview/:id',adminController.vendorView)
adminRouter.post('/vendorApproval',adminController.vendorApprove)
adminRouter.post('/addcategory',HotelController.Addcategory)
adminRouter.get('/getcategory',HotelController.getCategory)
adminRouter.get('/gethotelRequestData',HotelController.hotelDatarequestAdmin)
adminRouter.get('/gethotelData',HotelController.hotelDataAdmin)
adminRouter.post('/updateHotelproofstatus',HotelController.updateproofstatus)
module.exports=adminRouter