const express=require('express')
const userRouter=express.Router()
const admin=require('../models/Admin')
const vendor=require('../models/Vendor')
const upload=require('../middleWare/Multer')
const VendorController=require('../controllers/VendorController')
const UserController=require('../controllers/UserController')
const HotelController=require('../controllers/HotelController')
const PaymentController=require('../controllers/PaymentController')
const ChatController=require('../controllers/ChatController')
const couponController=require('../controllers/CouponController')
const auth=require('../middleWare/Auth')
const otpController =require('../controllers/otpController')



userRouter.post('/sendOTP',otpController.sendOTP)
userRouter.post('/OTPVerify',otpController.verifyOTP)

// userRouter.post('/otp',UserController.otpSending)
userRouter.post('/register',UserController.addUser)
userRouter.post('/login',UserController.UserLogin)
userRouter.get('/getprofile',auth.UserAuth,UserController.getProfile)
userRouter.patch('/edit',auth.UserAuth,UserController.editUserProfile)
userRouter.get('/bookings',auth.UserAuth,UserController.userBookings)
userRouter.get('/singlebookings',auth.UserAuth,UserController.userBookingsDetail)
userRouter.post('/reviewWriting',auth.UserAuth,UserController.reviewUpdating)
userRouter.post('/editphoto',auth.UserAuth,upload.single('image'),UserController.editProfilePhoto)
userRouter.post('/orders',auth.UserAuth,PaymentController.orderCreate)
userRouter.post('/walletPay',auth.UserAuth,PaymentController.walletpay)
userRouter.post('/verify',auth.UserAuth,PaymentController.verify)
userRouter.get('/chatCreate',auth.UserAuth,ChatController.createChat)
userRouter.post('/CreateMessage',auth.UserAuth,ChatController.createMessage)
userRouter.get('/Messages',auth.UserAuth,ChatController.getMessage)
userRouter.get('/bookingCancel',auth.UserAuth,UserController.CancelBooking)
userRouter.post('/applyCoupon',auth.UserAuth,couponController.applyCoupon)
userRouter.get('/userHoteldata',auth.UserAuth,HotelController.hotelDataUser)
userRouter.get('/singleHoteldata/:id',auth.UserAuth,HotelController.singleHotelData)
userRouter.get('/searchData',HotelController.getHotelsByPlaceAndName)

module.exports=userRouter