const express=require('express')
const userRouter=express.Router()
const admin=require('../models/Admin')
const vendor=require('../models/Vendor')
const upload=require('../middleWare/Multer')
// const multerMiddleware = require('../middleWare/Multer')
const VendorController=require('../controllers/VendorController')
const UserController=require('../controllers/UserController')
const HotelController=require('../controllers/HotelController')
const PaymentController=require('../controllers/PaymentController')
const ChatController=require('../controllers/ChatController')
// const otpController =require('../controllers/otpController')



// userRouter.post('/sendOTP',otpController.sendOTP)
userRouter.get('/userHoteldata',HotelController.hotelDataUser)
userRouter.get('/singleHoteldata/:id',HotelController.singleHotelData)
userRouter.post('/otp',UserController.otpSending)
userRouter.post('/register',UserController.addUser)
userRouter.post('/login',UserController.UserLogin)
userRouter.get('/getprofile',UserController.getProfile)
userRouter.patch('/edit',UserController.editUserProfile)
userRouter.get('/bookings',UserController.userBookings)
userRouter.get('/singlebookings',UserController.userBookingsDetail)
userRouter.post('/reviewWriting',UserController.reviewUpdating)
userRouter.post('/editphoto',upload.single('image'),UserController.editProfilePhoto)
userRouter.post('/orders',PaymentController.orderCreate)
userRouter.post('/verify',PaymentController.verify)
userRouter.get('/chatCreate',ChatController.createChat)
userRouter.post('/CreateMessage',ChatController.createMessage)
userRouter.get('/Messages',ChatController.getMessage)
userRouter.get('/bookingCancel',UserController.CancelBooking)


module.exports=userRouter