const express=require('express')
const vendorRouter=express.Router()
const admin=require('../models/Admin')
const vendor=require('../models/Vendor')
const VendorController=require('../controllers/VendorController')
const HotelController=require('../controllers/HotelController')
const upload=require('../middleWare/Multer')
// const multerMiddleware = require('../middleWare/Multer')
const Vendor=require('../middleWare/Auth')

vendorRouter.post('/vendorsignup',VendorController.addVendor)
vendorRouter.post('/vendorlogin',VendorController.VendorLogin)
 
vendorRouter.get('/vendorprofile',Vendor.VendorAuth,VendorController.getProfile)
vendorRouter.patch('/vendorprofile',VendorController.editVendorProfile)
vendorRouter.post('/addcategory',HotelController.Addcategory)
vendorRouter.get('/getcategory',HotelController.getCategory)
// vendorRouter.post('/vendorprofileimage',VendorController.getProfileimage)
// vendorRouter.get('/vendorprofileimages',VendorController.getProfileimages)
vendorRouter.post('/vendorprofile',upload.single('image'),VendorController.editProfile)
vendorRouter.post('/vendorproof',upload.single('proof'),VendorController.ProofData)
vendorRouter.post('/addHotel', upload.fields([{ name: 'license', maxCount: 1 },{ name:'images', maxCount: 10 }]),HotelController.AddHotel)
vendorRouter.get('/hotelDatas',HotelController.hotelData)
vendorRouter.get('/bookingDatas',VendorController.BookingData)
vendorRouter.get('/dashbord',VendorController.Dashbord)

module.exports=vendorRouter